import 'bootstrap/dist/css/bootstrap.css';
import './globals.css';

import Header from './header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout ({
  children,
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="p-3">
          {/* Add currentUser as props to all children */}
          {children}
        </div>
      </body>
    </html>
  );
}
