@url = ticketing.dev/api
@email = user123@test.com
@password = 12341234

@cookie = session=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJalkzTVdGaU1qTmhaakZoTXpGa01USTRPREkwTTJWaU1pSXNJbVZ0WVdsc0lqb2lkWE5sY2pFeU0wQjBaWE4wTG1OdmJTSXNJbWxoZENJNk1UY3lPVGd3TWpneE1IMC51OEhtLTJINGpmNjhET3dfaFRUZXJpRHhGSC03RWRUY3FRM1JhZlFQYXJZIn0=; path=/; secure; httponly

### POST signup
POST {{url}}/users/signup
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### GET tickets
GET {{url}}/tickets

### POST ticket
POST {{url}}/tickets
Cookie: {{cookie}}
Content-Type: application/json

{
    "title": "title",
    "price": 10
}
