@url = ticketing.dev/api/tickets
@email = user123@test.com
@password = 12341234

@cookie = session=eyJqd3QiOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJalkyWXpJME5HUXdNbVJqTUdaaE56SmlNelJoTVRjNU9TSXNJbVZ0WVdsc0lqb2lkWE5sY2pFeU0wQjBaWE4wTG1OdmJTSXNJbWxoZENJNk1UY3lOREF3TnpZek1uMC5JOUFNS2ZqTUx3bUppNG1EaTFQSGwyS1hfdE9ZMkNlUUxqUml6Q29FbDQ4In0=; path=/; secure; httponly

### POST signup
POST {{url}}/signup
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### GET tickets
GET {{url}}

### POST ticket
POST {{url}}
Cookie: {{cookie}}
Content-Type: application/json

{
    "title": "title",
    "price": 10
}
